<?php

namespace app\modules\v1\admin\models\form;

use yii\behaviors\TimestampBehavior;
use app\modules\v1\admin\models\Wage;

class WageForm extends Wage
{
    public function fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        return [
            ['status', 'in', 'range' => [0, 1], 'allowArray' => true],
            ['allowance_pay', "integer", 'min' => 1]
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => date("Y-m-d h:i:s"),
            ],
        ];
    }

}