<?php

namespace app\modules\v1\admin;

use app\modules\v1\admin\components\EventComponent;
use yii\base\Module;

class AdminModule extends Module
{
    public function init()
    {
        $this->components = [
            "eventComponent" => EventComponent::class
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors(): array
    {
        $behaviors['authenticator'] = [
            'class' => \yii\filters\auth\CompositeAuth::class,
            //  \yii\base\ActionFilter isActive()
            'except' => ['site/login'],
            'authMethods' => [
                \yii\filters\auth\HttpBearerAuth::class
            ],
        ];
        $behaviors['access'] = [
            'class' => \yii\filters\AccessControl::className(),
            'rules' => [
                // Get controller id by @var \yii\filters\AccessRule $
                [
                    'controllers' => ['v1/admin/site'],
                    'actions' => ['login', 'signup'],
                    'allow' => true,
                    'roles' => ['?'],
                ],
                [
                    'allow' => true,
                    'roles' => ['loginBackend'],
                ]
            ]
        ];
        return $behaviors;
    }
}