<?php

namespace app\modules\v1\admin;

use app\modules\v1\admin\components\EventComponent;
use yii\base\Module;

class AdminModule extends Module
{
    public function init()
    {
        $this->components = [
            "eventComponent" => EventComponent::class
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}