<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\query\base;

use Yii;

/**
 * This is the base-model class for table "staffs".
 *
 * @property integer $id
 * @property string $staff_code
 * @property string $fullname
 * @property string $phone
 * @property string $address
 * @property integer $staff_level
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $work_day
 * @property string $bank_account_name
 * @property integer $bank_account_number
 *
 * @property \app\models\query\StaffLevel $staffLevel
 * @property \app\models\query\Wage[] $wages
 * @property string $aliasModel
 */
abstract class Staff extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'staffs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['staff_code', 'fullname'], 'required'],
            [['staff_level', 'status', 'work_day', 'bank_account_number'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['staff_code', 'fullname', 'address', 'bank_account_name'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 20],
            [['staff_code'], 'unique'],
            [['staff_level'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\query\StaffLevel::className(), 'targetAttribute' => ['staff_level' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'staff_code' => Yii::t('models', 'Staff Code'),
            'fullname' => Yii::t('models', 'Fullname'),
            'phone' => Yii::t('models', 'Phone'),
            'address' => Yii::t('models', 'Address'),
            'staff_level' => Yii::t('models', 'Staff Level'),
            'status' => Yii::t('models', 'Status'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'deleted_at' => Yii::t('models', 'Deleted At'),
            'work_day' => Yii::t('models', 'Work Day'),
            'bank_account_name' => Yii::t('models', 'Bank Account Name'),
            'bank_account_number' => Yii::t('models', 'Bank Account Number'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStaffLevel()
    {
        return $this->hasOne(\app\models\query\StaffLevel::className(), ['id' => 'staff_level']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWages()
    {
        return $this->hasMany(\app\models\query\Wage::className(), ['staff_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\StaffQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\StaffQuery(get_called_class());
    }


}
