<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\query\base;

use Yii;

/**
 * This is the base-model class for table "wage_staffs".
 *
 * @property integer $id
 * @property integer $staff_id
 * @property string $level_text
 * @property integer $level_pay
 * @property integer $turnover_pay
 * @property integer $allowance_pay
 * @property integer $total_pay
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\query\Staff $staff
 * @property string $aliasModel
 */
abstract class WageStaff extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wage_staffs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['staff_id', 'level_pay', 'turnover_pay', 'allowance_pay', 'total_pay', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['level_text'], 'string', 'max' => 255],
            [['staff_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\query\Staff::className(), 'targetAttribute' => ['staff_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'staff_id' => Yii::t('models', 'Staff ID'),
            'level_text' => Yii::t('models', 'Level Text'),
            'level_pay' => Yii::t('models', 'Level Pay'),
            'turnover_pay' => Yii::t('models', 'Turnover Pay'),
            'allowance_pay' => Yii::t('models', 'Allowance Pay'),
            'total_pay' => Yii::t('models', 'Total Pay'),
            'status' => Yii::t('models', 'Status'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStaff()
    {
        return $this->hasOne(\app\models\query\Staff::className(), ['id' => 'staff_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\WageStaffQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\WageStaffQuery(get_called_class());
    }


}
