<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "customers".
 *
 * @property integer $id
 * @property string $customer_code
 * @property string $surrogate
 * @property string $name
 * @property string $phone
 * @property string $address
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Report[] $reports
 * @property \app\models\Wage[] $wages
 * @property string $aliasModel
 */
abstract class Customer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customers';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_code'], 'required'],
            [['status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['customer_code', 'surrogate', 'name', 'phone', 'address'], 'string', 'max' => 255],
            [['customer_code'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_code' => 'Staff Code',
            'surrogate' => 'Surrogate',
            'name' => 'Name',
            'phone' => 'Phone',
            'address' => 'Address',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated_at',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReports()
    {
        return $this->hasMany(\app\models\Report::className(), ['customer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWages()
    {
        return $this->hasMany(\app\models\Wage::className(), ['customer_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\CustomerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\CustomerQuery(get_called_class());
    }


}
