<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "reports".
 *
 * @property integer $id
 * @property string $report_title
 * @property string $report_content
 * @property integer $customer_id
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Customer $customer
 * @property string $aliasModel
 */
abstract class Report extends \yii\db\ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;
    const STATUS_DELETE = -99;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reports';
    }

    public function statusList($status)
    {
        return [
            self::STATUS_ACTIVE => "Active",
            self::STATUS_INACTIVE => "InActive",
            self::STATUS_DELETE => "Delete"
        ][$status];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['report_content'], 'string'],
            [['customer_id', 'status'], 'integer'],
            [['created_at', 'updated_at', 'done_at'], 'safe'],
            [['report_title'], 'string', 'max' => 255],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Customer::className(), 'targetAttribute' => ['customer_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'report_title' => 'Report Title',
            'report_content' => 'Report Content',
            'customer_id' => 'Customer ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\app\models\Customer::className(), ['id' => 'customer_id']);
    }



    /**
     * @inheritdoc
     * @return \app\models\ReportQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\ReportQuery(get_called_class());
    }

    public function getStatusText()
    {
        return $this->statusList($this->status);
    }
}
