<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "staffs".
 *
 * @property integer $id
 * @property string $staff_code
 * @property string $fullname
 * @property string $phone
 * @property string $address
 * @property integer $staff_level
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $bank_account_name
 * @property integer $bank_account_number
 * @property integer $work_day
 *
 * @property \app\models\StaffLevel $staffLevel
 * @property \app\models\Wage[] $wages
 * @property string $aliasModel
 */
abstract class Staff extends \yii\db\ActiveRecord
{
    const STATUS_DELETE = -99;
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'staffs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['staff_code', 'fullname'], 'required'],
            [['staff_level', 'status', 'work_day', 'bank_account_number', 'turnover'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['staff_code', 'fullname', 'address', 'bank_account_name'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 20],
            [['staff_code'], 'unique'],
            [['staff_level'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StaffLevel::className(), 'targetAttribute' => ['staff_level' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'staff_code' => 'Staff Code',
            'fullname' => 'Fullname',
            'phone' => 'Phone',
            'address' => 'Address',
            'staff_level' => 'Staff Level',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStaffLevel()
    {
        return $this->hasOne(\app\models\StaffLevel::className(), ['id' => 'staff_level']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWages()
    {
        return $this->hasMany(\app\models\Wage::className(), ['staff_id' => 'id']);
    }

    protected function getStaffLevelName()
    {
        return $this->staffLevel?->name;
    }


    /**
     * @inheritdoc
     * @return \app\models\StaffQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\StaffQuery(get_called_class());
    }
}
