<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "users".
 *
 * @property integer $id
 * @property string $email
 * @property integer $status
 * @property string $fullname
 * @property string $created_at
 * @property string $updated_at
 * @property string $logged_at
 * @property string $password_hash
 * @property string $auth_key
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'fullname'], 'required'],
            [['status'], 'integer'],
            [['created_at', 'updated_at', 'logged_at'], 'safe'],
            [['email', 'fullname', 'password_hash', 'auth_key'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'status' => 'Status',
            'fullname' => 'Fullname',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'logged_at' => 'Logged At',
            'password_hash' => 'Password Hash',
            'auth_key' => 'Auth Key',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\UserQuery(get_called_class());
    }


}
