<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wages".
 *
 * @property integer $id
 * @property integer $customer_id
 * @property integer $staff_id
 * @property integer $basic_pay
 * @property integer $piece_pay
 * @property integer $allowance_pay
 * @property integer $total_pay
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \app\models\Customer $customer
 * @property \app\models\Staff $staff
 * @property string $aliasModel
 */
abstract class Wage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wages';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['customer_id', 'staff_id'], 'required'],
            [['customer_id', 'staff_id', 'basic_pay', 'piece_pay', 'allowance_pay', 'total_pay', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Customer::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['staff_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Staff::className(), 'targetAttribute' => ['staff_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'customer_id' => 'Customer ID',
            'staff_id' => 'Staff ID',
            'basic_pay' => 'Basic Pay',
            'piece_pay' => 'Piece Pay',
            'allowance_pay' => 'Allowance Pay',
            'total_pay' => 'Total Pay',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(\app\models\Customer::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStaff()
    {
        return $this->hasOne(\app\models\Staff::className(), ['id' => 'staff_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\WageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\WageQuery(get_called_class());
    }


}
